spring:
  application:
    name: projects-service
  # Base de datos H2 en memoria para desarrollo local
  datasource:
    url: jdbc:h2:mem:projectsdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  # RabbitMQ - mantiene la conexi√≥n real
  rabbitmq:
    addresses: amqps://qmvnjeii:ynOJ4vgUqOr59E9nF1_elmycwIz-_oqU@campbell.lmq.cloudamqp.com:5671/qmvnjeii
    host: campbell.lmq.cloudamqp.com
    port: 5671
    username: qmvnjeii
    password: ynOJ4vgUqOr59E9nF1_elmycwIz-_oqU

springdoc:
  api-docs:
    path: /docs
server:
  port: 8080
  servlet:
    context-path: /api/v1/projects

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, prometheus

app:
  rabbitmq:
    project-events-exchange: project.events.exchange
    routing-key:
      created: project.created
      updated: project.updated
      deleted: project.deleted

