networks:
  projects-network:
    driver: bridge
    name: projects-network
  infrastructure-network:
    external: true
    name: infrastructure-network

volumes:
  postgres-projects-data:
    driver: local
  postgres-categorization-data:
    driver: local

services:
  # --- Base de Datos para Projects Service ---
  postgres_projects:
    image: postgres:15-alpine
    container_name: postgres_projects
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-projects-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=projects_db
      - POSTGRES_USER=projects_user
      - POSTGRES_PASSWORD=projects_password
    networks:
      - projects-network


  # --- Microservicios ---

  projects-service:
    build:
      context: ./projects-service
    container_name: projects-service
    restart: unless-stopped
    ports:
      - "8071:8071"
    networks:
      - projects-network
      - infrastructure-network
    depends_on:
      - postgres_projects
    environment:
      - SERVER_PORT=8071
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_projects:5432/projects_db
      - SPRING_DATASOURCE_USERNAME=projects_user
      - SPRING_DATASOURCE_PASSWORD=projects_password
      - SPRING_RABBITMQ_HOST=rabbitmq-udeajobs
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - APP_RABBITMQ_PROJECT_EVENTS_EXCHANGE=project.events.exchange
      - APP_RABBITMQ_ROUTING_KEY_CREATED=project.created
      - APP_RABBITMQ_ROUTING_KEY_UPDATED=project.updated
      - APP_RABBITMQ_ROUTING_KEY_DELETED=project.deleted

  categorization-service:
    build:
      context: ./categorization-service
    container_name: categorization-service
    restart: unless-stopped
    env_file:
      - ./categorization-service/.env
    networks:
      - projects-network
      - infrastructure-network
    environment:
      - RABBITMQ_HOST=rabbitmq-udeajobs
      - PROJECT_EXCHANGE=project.events.exchange 
      - ROUTING_KEY_CREATED=project.created
      - ROUTING_KEY_UPDATED=project.updated
      - GROQ_API_URL=https://api.groq.com/openai/v1/chat/completions
      - GROQ_MODEL=llama-3.1-8b-instant