networks:
  projects-network:
    driver: bridge
    name: projects-network
  infrastructure-network:
    external: true
    name: infrastructure-network

volumes:
  postgres-projects-data:
    driver: local
  elasticsearch-data:
    driver: local

services:
  # --- Base de Datos para Projects Service ---
  postgres_projects:
    image: postgres:15-alpine
    container_name: postgres_projects
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-projects-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=projects_db
      - POSTGRES_USER=projects_user
      - POSTGRES_PASSWORD=projects_password
    networks:
      - projects-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # <-- Deshabilita la seguridad
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Limita la RAM
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - projects-network


  # --- Microservicios ---

  projects-gateway:
    build:
      context: ./projects-gateway 
    container_name: projects-gateway
    restart: unless-stopped
    ports:
      - "80:8080" 
    networks:
      - projects-network
      - infrastructure-network
    environment:
      - PROJECTS_SERVICE_URL=http://projects-service:8080
      - SEARCH_SERVICE_URL=http://searching-service:8080
      - JWT_SECRET="7NG5umhwfjKJDAqa53AlX1vNOypdUlUG4b/CuN8Wja8="

  projects-service:
    build:
      context: ./projects-service
    container_name: projects-service
    restart: unless-stopped
    networks:
      - projects-network
      - infrastructure-network
    depends_on:
      - postgres_projects
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_projects:5432/projects_db
      - SPRING_DATASOURCE_USERNAME=projects_user
      - SPRING_DATASOURCE_PASSWORD=projects_password
      - SPRING_RABBITMQ_HOST=rabbitmq-udeajobs
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - PROJECT_EVENTS_EXCHANGE=project.events.exchange
      - ROUTING_KEY_CREATED=project.created
      - ROUTING_KEY_UPDATED=project.updated
      - ROUTING_KEY_DELETED=project.deleted

  categorization-service:
    build:
      context: ./categorization-service
    container_name: categorization-service
    restart: unless-stopped
    env_file:
      - ./categorization-service/.env
    networks:
      - projects-network
      - infrastructure-network
    environment:
      - RABBITMQ_HOST=rabbitmq-udeajobs
      - PROJECT_EXCHANGE=project.events.exchange 
      - ROUTING_KEY_CREATED=project.created
      - ROUTING_KEY_UPDATED=project.updated
      - GROQ_API_URL=https://api.groq.com/openai/v1/chat/completions
      - GROQ_MODEL=llama-3.1-8b-instant
  
  searching-service:
    build:
      context: ./searching-service 
    container_name: searching-service
    restart: unless-stopped
    networks:
      - projects-network
      - infrastructure-network
    depends_on:
      - elasticsearch   
    environment:
      # --- Conexión a Elasticsearch ---
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      # --- Conexión a RabbitMQ ---
      - RABBITMQ_HOST=rabbitmq-udeajobs
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      # --- Nombres de la App ---
      - ELASTICSEARCH_INDEX_NAME=projects
      - PROJECT_QUEUE=searchproject.created.queue
      - CATEGORIZATION_QUEUE=searchproject.categorized.queue
      - PROJECT_EXCHANGE=project.events.exchange
      - CATEGORIZATION_EXCHANGE=project.events.exchange
      - PROJECT_ROUTING_KEY=project.created
      - CATEGORIZATION_ROUTING_KEY=project.categorized